from dataclasses import dataclass
from collections.abc import Mapping
import re


_TEMPLATE_TOKEN = re.compile(r"\{([^{}]+)\}")
_MAX_TEMPLATE_LENGTH = 2000


@dataclass(frozen=True)
class TemplateDefinition:
    command: str
    scenario: str
    label: str
    default: str
    variables: tuple[str, ...]


TEMPLATE_DEFINITIONS = (
    TemplateDefinition("/入职", "joined", "入职成功", "{昵称}，欢迎入职摸鱼公司。你的工号：{工号}。当前余额：{余额} {货币}。", ("{昵称}", "{工号}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/入职", "already_joined", "已入职", "{昵称}已经在职，当前余额：{余额} {货币}。", ("{昵称}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/入职", "missing_name", "缺少昵称", "请用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/入职", "name_taken", "名称已占用", "名称已被占用。", ("{日期}",)),
    TemplateDefinition("/打卡", "checked_in", "打卡成功", "打卡成功，领取 {打卡奖励} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{余额}", "{打卡奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/打卡", "already_checked_in", "今日已打卡", "今天已经打过卡啦，明天再来。", ("{昵称}", "{日期}")),
    TemplateDefinition("/打卡", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/余额", "shown", "查询成功", "{昵称}，当前余额：{余额} {货币}。", ("{昵称}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/余额", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/发奖金", "usage", "指令格式", "请回复目标员工发送 /发奖金 金额，或使用 /发奖金 员工名 金额、/发奖金 全部 金额。", ("{日期}",)),
    TemplateDefinition("/发奖金", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/发奖金", "not_authorized", "无发放权限", "只有核心董事会成员可以发放奖金。", ("{日期}",)),
    TemplateDefinition("/发奖金", "invalid_amount", "金额无效", "奖金金额必须是 1–99999 的整数。", ("{日期}",)),
    TemplateDefinition("/发奖金", "target_not_found", "员工不存在", "未找到该员工，请检查员工名。", ("{日期}",)),
    TemplateDefinition("/发奖金", "ambiguous_target", "员工重名", "存在多名同名员工：{候选员工}。请使用工号后重试。", ("{候选员工}", "{日期}")),
    TemplateDefinition("/发奖金", "single_granted", "单人奖金已发放", "【奖金】{发放者}向{收款人}发放 {金额} {货币}。", ("{发放者}", "{收款人}", "{金额}", "{货币}", "{日期}")),
    TemplateDefinition("/发奖金", "all_granted", "全员奖金已发放", "【奖金】{发放者}向全体 {人数} 名员工每人发放 {金额} {货币}。", ("{发放者}", "{人数}", "{金额}", "{货币}", "{日期}")),
    TemplateDefinition("/发红包", "usage", "指令格式", "请用 /发红包 人数 总金额 创建红包。", ("{日期}",)),
    TemplateDefinition("/发红包", "group_only", "仅限群聊", "请回到群里发送 /发红包 人数 总金额。", ("{日期}",)),
    TemplateDefinition("/发红包", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/发红包", "disabled", "玩法关闭", "当前群聊已关闭小游戏功能。", ("{日期}",)),
    TemplateDefinition("/发红包", "invalid_parameters", "参数无效", "红包人数必须是 2–50，总金额必须是人数至 99999 的半角整数。", ("{日期}",)),
    TemplateDefinition("/发红包", "insufficient_balance", "余额不足", "余额不足，无法发出这个红包。", ("{日期}",)),
    TemplateDefinition("/发红包", "daily_limit", "次数用尽", "你今天的 5 次发红包机会已经用完了。", ("{日期}",)),
    TemplateDefinition("/发红包", "active_packet", "已有红包", "当前还有一个红包未结束，请抢完或等待过期。", ("{日期}",)),
    TemplateDefinition("/发红包", "created", "红包已发出", "【随机运气红包】{发起者}发出 {人数} 份共 {总金额} {货币}的红包，{过期分钟} 分钟内发送 /抢红包。", ("{发起者}", "{人数}", "{总金额}", "{过期分钟}", "{货币}", "{日期}")),
    TemplateDefinition("/发红包", "expired", "红包过期", "【随机运气红包已过期】{发起者}发出的红包已领取 {已领份数}/{人数} 份，未领取金额已退回 {退款金额} {货币}。", ("{发起者}", "{已领份数}", "{人数}", "{退款金额}", "{货币}", "{日期}")),
    TemplateDefinition("/抢红包", "group_only", "仅限群聊", "请回到群里发送 /抢红包。", ("{日期}",)),
    TemplateDefinition("/抢红包", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/抢红包", "no_active_packet", "暂无红包", "当前没有可以领取的红包。", ("{日期}",)),
    TemplateDefinition("/抢红包", "already_claimed", "已经领取", "你已经领取过这个红包了。", ("{日期}",)),
    TemplateDefinition("/抢红包", "claimed", "领取成功", "{领取者}抢到 {领取金额}，剩余 {剩余份数}/{人数} 份。", ("{领取者}", "{领取金额}", "{剩余份数}", "{人数}", "{日期}")),
    TemplateDefinition("/抢红包", "completed", "红包结算", "【随机运气红包已抢完】\n{领取结果}\n手气最佳：{手气最佳}\n手气最差：{手气最差}", ("{领取结果}", "{手气最佳}", "{手气最差}", "{日期}")),
    TemplateDefinition("/我", "shown", "个人状态", "{昵称}\n工号：{工号}\n职位：{职位}（{职级}）\n部门：{部门}\n当前余额：{余额} {货币}。\n今日活跃度：{活跃等级}。\n今日收益：{今日收益} {货币}。\n连续打卡：{连续打卡天数} 天。", ("{昵称}", "{工号}", "{职位}", "{职级}", "{部门}", "{余额}", "{货币}", "{活跃等级}", "{今日收益}", "{连续打卡天数}", "{日期}")),
    TemplateDefinition("/我", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/修改名称", "usage", "修改格式", "请用 /修改名称 新名称 修改自己的名称。", ("{日期}",)),
    TemplateDefinition("/修改名称", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/修改名称", "invalid_name", "名称无效", "名称长度必须为 1–64 个字符。", ("{日期}",)),
    TemplateDefinition("/修改名称", "name_taken", "名称已占用", "名称已被占用。", ("{日期}",)),
    TemplateDefinition("/修改名称", "unchanged", "名称未变化", "名称没有变化。", ("{日期}",)),
    TemplateDefinition("/修改名称", "renamed", "修改成功", "名称已修改：{旧名称} → {新名称}。", ("{旧名称}", "{新名称}", "{日期}")),
    TemplateDefinition("/编辑档案", "usage", "编辑格式", "请用 /编辑档案 档案内容 更新个人档案。", ("{日期}",)),
    TemplateDefinition("/编辑档案", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/编辑档案", "too_long", "档案过长", "个人档案不能超过 800 个字符。", ("{日期}",)),
    TemplateDefinition("/编辑档案", "unchanged", "档案未变化", "档案内容没有变化。", ("{日期}",)),
    TemplateDefinition("/编辑档案", "insufficient_balance", "余额不足", "余额不足，编辑档案需要 {编辑费用} {货币}。", ("{编辑费用}", "{货币}", "{日期}")),
    TemplateDefinition("/编辑档案", "insufficient_labor", "公共人力不足", "当前公共人力不足，暂时无法编辑档案。", ("{日期}",)),
    TemplateDefinition("/编辑档案", "updated", "编辑成功", "个人档案已更新。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "usage", "编辑格式", "请回复一张图片后发送 /编辑档案形象。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "profile_required", "缺少个人档案", "请先完成个人档案，再设置档案形象。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "unchanged", "形象未变化", "档案形象没有变化。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "insufficient_balance", "余额不足", "余额不足，编辑档案形象需要 {编辑费用} {货币}。", ("{编辑费用}", "{货币}", "{日期}")),
    TemplateDefinition("/编辑档案形象", "insufficient_labor", "公共人力不足", "当前公共人力不足，暂时无法编辑档案形象。", ("{日期}",)),
    TemplateDefinition("/编辑档案形象", "updated", "编辑成功", "档案形象已更新。", ("{日期}",)),
    TemplateDefinition("/我的档案", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/我的档案", "empty", "尚未填写", "你还没有填写个人档案，请发送 /编辑档案 档案内容", ("{日期}",)),
    TemplateDefinition("/我的档案", "shown", "查看成功", "{档案内容}", ("{档案内容}", "{日期}")),
    TemplateDefinition("/我的物品", "shown", "查询成功", "{昵称}的物品：\n{物品列表}", ("{昵称}", "{物品列表}", "{日期}")),
    TemplateDefinition("/我的物品", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/我的物品", "group_only", "仅限群聊", "请回到群里发送 /我的物品。", ("{日期}",)),
    TemplateDefinition("/商店", "items_available", "商店有货", "总监事小卖部：\n{商店列表}", ("{商店列表}", "{日期}")),
    TemplateDefinition("/商店", "empty", "商店为空", "总监事小卖部还没有上架商品。", ("{日期}",)),
    TemplateDefinition("/商店", "group_only", "仅限群聊", "请回到群里发送 /商店。", ("{日期}",)),
    TemplateDefinition("/购买", "group_only", "仅限群聊", "请回到群里发送 /购买 商品序号。", ("{日期}",)),
    TemplateDefinition("/购买", "usage", "指令格式", "请用 /购买 商品序号，例如 /购买 1。", ("{日期}",)),
    TemplateDefinition("/购买", "purchased", "购买成功", "已购买 #{商品编号} {商品名称}，当前持有 {数量} 张，余额 {余额} {货币}。", ("{商品编号}", "{商品名称}", "{数量}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/购买", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/购买", "wrong_group", "群聊不可用", "当前群聊无法使用商店。", ("{日期}",)),
    TemplateDefinition("/购买", "not_found", "商品不存在", "没有找到这个商品序号。", ("{日期}",)),
    TemplateDefinition("/购买", "disabled", "商品停用", "该商品当前已停用。", ("{日期}",)),
    TemplateDefinition("/购买", "adult_disabled", "成人商品关闭", "当前群聊未开启成人向商店玩法。", ("{日期}",)),
    TemplateDefinition("/购买", "rank_required", "职位不足", "购买该商品需要达到 LV{最低职位}。", ("{最低职位}", "{日期}")),
    TemplateDefinition("/购买", "out_of_stock", "库存不足", "该商品已经售罄。", ("{日期}",)),
    TemplateDefinition("/购买", "insufficient_balance", "余额不足", "余额不足，当前余额 {余额} {货币}。", ("{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/购买", "daily_limit", "今日限购", "你今天购买这一类商品的次数已经用完。", ("{日期}",)),
    TemplateDefinition("/使用", "group_only", "仅限群聊", "请回到群里发送 /使用 商品序号。", ("{日期}",)),
    TemplateDefinition("/使用", "usage", "指令格式", "请用 /使用 商品序号；对他人使用时请回复对方消息。", ("{日期}",)),
    TemplateDefinition("/使用", "gift_completed", "赠送成功", "已使用 #{商品编号} {商品名称}，{目标员工}收到 {奖励} {货币}。", ("{商品编号}", "{商品名称}", "{目标员工}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/使用", "scratch_completed", "刮奖成功", "已使用 #{商品编号} {商品名称}，刮出 {奖励} {货币}。", ("{商品编号}", "{商品名称}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/使用", "quota_completed", "次数增加", "已使用 #{商品编号} {商品名称}，今天的额外次数 +1。", ("{商品编号}", "{商品名称}", "{日期}")),
    TemplateDefinition("/使用", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/使用", "wrong_group", "群聊不可用", "当前群聊无法使用商店物品。", ("{日期}",)),
    TemplateDefinition("/使用", "not_found", "商品不存在", "没有找到这个商品序号。", ("{日期}",)),
    TemplateDefinition("/使用", "not_owned", "未持有", "你没有持有这件商品。", ("{日期}",)),
    TemplateDefinition("/使用", "no_effect", "没有使用效果", "这是收藏类商品，没有可执行的使用效果，物品未消耗。", ("{日期}",)),
    TemplateDefinition("/使用", "target_required", "需要回复目标", "请回复另一名已入职员工的消息后发送 /使用 商品序号。", ("{日期}",)),
    TemplateDefinition("/使用", "target_not_joined", "目标未入职", "被回复的人不是已入职员工。", ("{日期}",)),
    TemplateDefinition("/使用", "self_target", "不能对自己使用", "这张卡不能对自己使用。", ("{日期}",)),
    TemplateDefinition("/使用", "adult_required", "进入授权流程", "该商品需要进入场景与授权流程。", ("{日期}",)),
    TemplateDefinition("/使用", "not_adult", "不是成人卡", "该商品不需要场景授权流程。", ("{日期}",)),
    TemplateDefinition("/使用", "adult_disabled", "成人商品关闭", "当前群聊未开启成人向商店玩法。", ("{日期}",)),
    TemplateDefinition("/使用", "direct_chat_required", "需要私聊", "请先私聊总监事发送任意消息，建立可送达的私聊房间。", ("{日期}",)),
    TemplateDefinition("/使用", "common_active", "状态冲突", "该员工当前已有一条生效中的常识改变状态。", ("{日期}",)),
    TemplateDefinition("/使用", "scene_required", "等待填写场景", "卡片局 #{卡片局编号} 已创建，场景填写提示已私聊发送；30 分钟内有效。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/使用", "setup_active", "已有填写流程", "你已有卡片局 #{卡片局编号} 正在填写或选择参与者，请先完成或发送 /取消使用 {卡片局编号}。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/使用", "unsupported", "暂不可用", "该商品当前无法使用。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "group_only", "仅限群聊", "请回到群里回复目标员工发送 /邀请参与 卡片局编号。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "usage", "指令格式", "请回复目标员工发送 /邀请参与 卡片局编号。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "participant_added", "邀请成功", "已将该员工加入卡片局 #{卡片局编号}。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/邀请参与", "awaiting_consent", "人数已齐", "卡片局 #{卡片局编号} 人数已齐，授权通知已发出。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/邀请参与", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "session_not_found", "卡片局不存在", "没有找到该卡片局。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "wrong_group", "来源群不匹配", "该卡片局不属于当前群，请回到发起它的群聊操作。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "not_owner", "不是发起人", "只有卡片局发起人可以邀请参与者。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "cannot_invite", "当前不可邀请", "该卡片局当前不能继续邀请。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "expired", "填写已超时", "卡片局 #{卡片局编号} 的填写或选人时间已结束，预留卡片已退回。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/邀请参与", "target_required", "需要回复目标", "请回复目标员工的消息后发送邀请指令。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "target_not_joined", "目标未入职", "被回复的人不是已入职员工。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "self_target", "不能邀请自己", "不能把自己作为额外参与者。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "duplicate_target", "已经邀请", "该员工已经在此卡片局中。", ("{日期}",)),
    TemplateDefinition("/邀请参与", "participants_full", "人数已满", "该卡片局人数已经补齐。", ("{日期}",)),
    TemplateDefinition("/取消使用", "group_only", "仅限群聊", "请回到群里发送 /取消使用 卡片局编号。", ("{日期}",)),
    TemplateDefinition("/取消使用", "usage", "指令格式", "请用 /取消使用 卡片局编号。", ("{日期}",)),
    TemplateDefinition("/取消使用", "cancelled", "取消成功", "卡片局 #{卡片局编号} 已取消，预留卡片已退回。", ("{卡片局编号}", "{日期}")),
    TemplateDefinition("/取消使用", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/取消使用", "session_not_found", "卡片局不存在", "没有找到该卡片局。", ("{日期}",)),
    TemplateDefinition("/取消使用", "wrong_group", "来源群不匹配", "该卡片局不属于当前群，请回到发起它的群聊操作。", ("{日期}",)),
    TemplateDefinition("/取消使用", "not_owner", "不是发起人", "只有卡片局发起人可以取消。", ("{日期}",)),
    TemplateDefinition("/取消使用", "cannot_cancel", "不可取消", "该卡片局已经进入授权或效果阶段，不能取消。", ("{日期}",)),
    *(
        TemplateDefinition(command, "group_only", "仅限群聊", "请在群里回复对应授权通知使用该指令。", ("{日期}",))
        for command in ("/同意使用", "/拒绝使用")
    ),
    *(
        definition
        for command in ("/同意使用", "/拒绝使用")
        for definition in (
            TemplateDefinition(command, "authorization_reply_required", "需要回复授权", "请回复发给你的对应授权通知。", ("{日期}",)),
            TemplateDefinition(command, "authorization_not_found", "授权不存在", "没有找到与你和该回复对应的待授权记录。", ("{日期}",)),
            TemplateDefinition(command, "wrong_group", "来源群不匹配", "请回到授权通知所在的来源群进行确认。", ("{日期}",)),
            TemplateDefinition(command, "already_finished", "流程已结束", "该卡片局已经结束。", ("{日期}",)),
            TemplateDefinition(command, "expired", "授权已超时", "卡片局 #{卡片局编号} 的授权时间已结束，本局已作废。", ("{卡片局编号}", "{日期}")),
            TemplateDefinition(command, "already_decided", "已经决定", "你的授权选择已经记录，不能重复修改。", ("{日期}",)),
            TemplateDefinition(command, "approved_waiting", "同意已记录", "卡片局 #{卡片局编号}：你的同意已记录，等待其他参与者。", ("{卡片局编号}", "{日期}")),
            TemplateDefinition(command, "all_approved", "全部同意", "卡片局 #{卡片局编号}：全部参与者已同意，效果开始处理。", ("{卡片局编号}", "{日期}")),
            TemplateDefinition(command, "rejected", "拒绝已记录", "卡片局 #{卡片局编号} 已因拒绝作废。", ("{卡片局编号}", "{日期}")),
            TemplateDefinition(command, "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
        )
    ),
    TemplateDefinition("/帮助", "shown", "帮助回复", "总监事指令簿：\n{指令列表}", ("{指令列表}", "{日期}")),
    TemplateDefinition("/当前游戏", "shown", "当前游戏", "当前游戏：{游戏}\n状态：{状态}\n你的身份：{身份}\n参与者：{参与者}\n可用指令：{可用指令}", ("{游戏}", "{状态}", "{身份}", "{参与者}", "{可用指令}", "{日期}")),
    TemplateDefinition("/当前游戏", "none", "暂无游戏", "当前没有进行中的游戏。", ("{日期}",)),
    TemplateDefinition("/当前游戏", "conflict", "状态冲突", "检测到多个活动游戏，请联系管理员处理。", ("{日期}",)),
    TemplateDefinition("/加入", "joined", "报名成功", "{昵称} 已加入随机事件，担任 {角色}。\n剩余可选身份：{剩余席位}", ("{昵称}", "{角色}", "{剩余席位}", "{日期}")),
    TemplateDefinition("/加入", "started", "事件开始", "{昵称}已加入，人员已齐，随机事件开始。", ("{昵称}", "{日期}")),
    TemplateDefinition("/加入", "no_event", "暂无事件", "当前没有可报名的随机事件。", ("{日期}",)),
    TemplateDefinition("/加入", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/加入", "invalid", "报名方式", "请用 /加入 角色 报名。", ("{日期}",)),
    TemplateDefinition("/加入", "failed", "报名失败", "{原因}", ("{原因}", "{日期}")),
    TemplateDefinition("/部门", "shown", "部门列表", "部门列表：\n{部门列表}", ("{部门列表}", "{日期}")),
    TemplateDefinition("/部门人数", "shown", "全部部门人数", "【部门人数统计】\n{部门统计}", ("{部门统计}", "{日期}")),
    TemplateDefinition("/部门人数", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/我的部门人数", "shown", "我的部门人数", "【我的部门人数统计】\n{部门统计}", ("{部门统计}", "{日期}")),
    TemplateDefinition("/我的部门人数", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/加入部门", "requested", "加入申请已提交", "{昵称}已提交加入{部门}申请，等待该部门更高职位成员审批。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/加入部门", "joined", "董事会直接加入", "{昵称}已直接加入{部门}。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/加入部门", "usage", "部门名称缺失", "请用 /加入部门 部门名 加入部门。", ("{日期}",)),
    TemplateDefinition("/加入部门", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/加入部门", "already_assigned", "已有部门", "你已加入部门，请使用 /切换部门 部门名。", ("{日期}",)),
    TemplateDefinition("/加入部门", "unknown_department", "部门不可用", "该部门不存在或暂未开放。", ("{日期}",)),
    TemplateDefinition("/加入部门", "already_pending", "已有待审申请", "你已有一条待审批的部门申请，请耐心等待。", ("{日期}",)),
    TemplateDefinition("/切换部门", "requested", "切换申请已提交", "{昵称}已提交切换至{部门}申请，等待该部门更高职位成员审批。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/切换部门", "switched", "董事会直接切换", "{昵称}已直接切换至{部门}。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/切换部门", "usage", "部门名称缺失", "请用 /切换部门 部门名 切换部门。", ("{日期}",)),
    TemplateDefinition("/切换部门", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/切换部门", "must_join_first", "尚未加入部门", "你当前尚未分配部门，请使用 /加入部门 部门名。", ("{日期}",)),
    TemplateDefinition("/切换部门", "already_in_department", "部门未变更", "你当前已在该部门。", ("{日期}",)),
    TemplateDefinition("/切换部门", "unknown_department", "部门不可用", "该部门不存在或暂未开放。", ("{日期}",)),
    TemplateDefinition("/切换部门", "already_pending", "已有待审申请", "你已有一条待审批的部门申请，请耐心等待。", ("{日期}",)),
    TemplateDefinition("/部门申请列表", "shown", "待审部门申请", "{申请列表}", ("{申请列表}", "{日期}")),
    TemplateDefinition("/部门申请列表", "empty", "暂无申请", "当前没有你可处理的部门申请。", ("{日期}",)),
    TemplateDefinition("/同意部门", "approved", "部门申请已同意", "{昵称}已加入{部门}。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/同意部门", "usage", "申请编号格式", "请用 /同意部门 1 2 3 审批申请。", ("{日期}",)),
    TemplateDefinition("/同意部门", "empty", "暂无申请", "当前没有你可处理的部门申请。", ("{日期}",)),
    TemplateDefinition("/同意部门", "unavailable", "申请不可处理", "该部门申请不可处理。", ("{日期}",)),
    TemplateDefinition("/全部同意部门", "approved", "部门申请已同意", "{昵称}已加入{部门}。", ("{昵称}", "{部门}", "{日期}")),
    TemplateDefinition("/全部同意部门", "empty", "暂无申请", "当前没有你可处理的部门申请。", ("{日期}",)),
    TemplateDefinition("/全部同意部门", "unavailable", "申请不可处理", "该部门申请不可处理。", ("{日期}",)),
    TemplateDefinition("/拒绝部门", "rejected", "已拒绝", "已拒绝{昵称}的部门申请。", ("{昵称}", "{日期}")),
    TemplateDefinition("/拒绝部门", "usage", "申请编号格式", "请用 /拒绝部门 1 2 3 审批申请。", ("{日期}",)),
    TemplateDefinition("/拒绝部门", "empty", "暂无申请", "当前没有你可处理的部门申请。", ("{日期}",)),
    TemplateDefinition("/拒绝部门", "unavailable", "申请不可处理", "该部门申请不可处理。", ("{日期}",)),
    TemplateDefinition("/全部拒绝部门", "rejected", "已拒绝", "已拒绝{昵称}的部门申请。", ("{昵称}", "{日期}")),
    TemplateDefinition("/全部拒绝部门", "empty", "暂无申请", "当前没有你可处理的部门申请。", ("{日期}",)),
    TemplateDefinition("/全部拒绝部门", "unavailable", "申请不可处理", "该部门申请不可处理。", ("{日期}",)),
    TemplateDefinition("/职位", "shown", "职位列表", "职位列表：\n{职位列表}", ("{职位列表}", "{日期}")),
    TemplateDefinition("/晋升", "requested", "晋升申请已提交", "{昵称}已提交晋升申请：{当前职位} → {目标职位}，需要 {晋升价格} {货币}。", ("{昵称}", "{当前职位}", "{目标职位}", "{晋升价格}", "{货币}", "{日期}")),
    TemplateDefinition("/晋升", "already_pending", "已有申请", "你已有一条待审批的晋升申请，请耐心等待。", ("{日期}",)),
    TemplateDefinition("/晋升", "no_next_rank", "不可晋升", "你当前没有可申请的下一档职位。", ("{日期}",)),
    TemplateDefinition("/晋升", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/晋升申请列表", "shown", "待审申请", "{申请列表}", ("{申请列表}", "{日期}")),
    TemplateDefinition("/晋升申请列表", "empty", "暂无申请", "当前没有你可处理的晋升申请。", ("{日期}",)),
    TemplateDefinition("/同意", "approved", "晋升成功", "{昵称}已晋升为{目标职位}，扣除 {晋升价格} {货币}。", ("{昵称}", "{目标职位}", "{晋升价格}", "{货币}", "{日期}")),
    TemplateDefinition("/同意", "usage", "申请编号格式", "请用 /同意 1 2 3 审批申请。", ("{日期}",)),
    TemplateDefinition("/同意", "empty", "暂无申请", "当前没有你可处理的晋升申请。", ("{日期}",)),
    TemplateDefinition("/同意", "insufficient_balance", "余额不足", "你的摸鱼币不够呢。", ("{日期}",)),
    TemplateDefinition("/同意", "unavailable", "申请不可处理", "该晋升申请不可处理。", ("{日期}",)),
    TemplateDefinition("/全部同意", "approved", "晋升成功", "{昵称}已晋升为{目标职位}，扣除 {晋升价格} {货币}。", ("{昵称}", "{目标职位}", "{晋升价格}", "{货币}", "{日期}")),
    TemplateDefinition("/全部同意", "empty", "暂无申请", "当前没有你可处理的晋升申请。", ("{日期}",)),
    TemplateDefinition("/全部同意", "insufficient_balance", "余额不足", "你的摸鱼币不够呢。", ("{日期}",)),
    TemplateDefinition("/全部同意", "unavailable", "申请不可处理", "该晋升申请不可处理。", ("{日期}",)),
    TemplateDefinition("/拒绝", "rejected", "已拒绝", "已拒绝{昵称}的晋升申请。", ("{昵称}", "{日期}")),
    TemplateDefinition("/拒绝", "usage", "申请编号格式", "请用 /拒绝 1 2 3 审批申请。", ("{日期}",)),
    TemplateDefinition("/拒绝", "empty", "暂无申请", "当前没有你可处理的晋升申请。", ("{日期}",)),
    TemplateDefinition("/拒绝", "unavailable", "申请不可处理", "该晋升申请不可处理。", ("{日期}",)),
    TemplateDefinition("/全部拒绝", "rejected", "已拒绝", "已拒绝{昵称}的晋升申请。", ("{昵称}", "{日期}")),
    TemplateDefinition("/全部拒绝", "empty", "暂无申请", "当前没有你可处理的晋升申请。", ("{日期}",)),
    TemplateDefinition("/全部拒绝", "unavailable", "申请不可处理", "该晋升申请不可处理。", ("{日期}",)),
    TemplateDefinition("/退出", "rewarded", "领取奖励", "{昵称}完成目标，领取 {事件奖励} {货币}。", ("{昵称}", "{事件奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/退出", "left", "退出事件", "{昵称}已退出随机事件，未达到奖励条件。", ("{昵称}", "{日期}")),
    TemplateDefinition("/退出", "signup_left", "取消报名", "{昵称}已退出随机事件报名。", ("{昵称}", "{日期}")),
    TemplateDefinition("/退出", "no_event", "暂无事件", "当前没有可退出的随机事件。", ("{日期}",)),
    TemplateDefinition("/退出", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/退出", "failed", "退出失败", "{原因}", ("{原因}", "{日期}")),
    TemplateDefinition("/随机事件打赏", "opened", "进入打赏阶段", "【随机事件：{场景名称}】剧情阶段已结束，进入打赏环节（{打赏秒数} 秒）。\n可打赏员工：\n{参与者与基础奖励列表}\n发送：/打赏 员工名称 金额", ("{场景名称}", "{打赏秒数}", "{参与者与基础奖励列表}", "{日期}")),
    TemplateDefinition("/随机事件打赏", "settled", "自动结束汇总", "【随机事件打赏结束】\n{参与者打赏汇总}\n{无人打赏提示}", ("{参与者打赏汇总}", "{无人打赏提示}", "{日期}")),
    TemplateDefinition("/随机事件打赏", "forced_settled", "强制结束汇总", "【随机事件打赏已强制结束】\n{参与者打赏汇总}\n{无人打赏提示}", ("{参与者打赏汇总}", "{无人打赏提示}", "{日期}")),
    TemplateDefinition("/打赏", "usage", "打赏格式", "请用 /打赏 员工名称 金额。", ("{日期}",)),
    TemplateDefinition("/打赏", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/打赏", "no_tipping_event", "不在打赏阶段", "当前不在随机事件打赏阶段。", ("{日期}",)),
    TemplateDefinition("/打赏", "expired", "打赏已结束", "随机事件打赏阶段已结束。", ("{日期}",)),
    TemplateDefinition("/打赏", "invalid_amount", "金额无效", "打赏金额必须是正整数。", ("{日期}",)),
    TemplateDefinition("/打赏", "recipient_not_found", "员工不存在", "未找到该员工。", ("{日期}",)),
    TemplateDefinition("/打赏", "recipient_not_participant", "非参与者", "该员工不是本场随机事件参与者。", ("{日期}",)),
    TemplateDefinition("/打赏", "self_tip", "禁止自赏", "不能给自己打赏。", ("{日期}",)),
    TemplateDefinition("/打赏", "insufficient_balance", "余额不足", "余额不足，当前余额：{余额} {货币}。", ("{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/打赏", "tipped", "打赏成功", "{打赏者} 向 {收款人} 打赏了 {金额} {货币}。", ("{打赏者}", "{收款人}", "{金额}", "{货币}", "{日期}")),
    TemplateDefinition("/打赏", "failed", "打赏失败", "打赏失败，请稍后重试。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "usage", "玩法说明", "请用 /开始摸鱼躲藏 发起游戏，再用 /躲 编号 选择地点。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "blocked", "随机事件进行中", "当前随机事件正在报名或进行中，暂时不能发起躲猫猫。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "disabled", "玩法未开启", "躲猫猫玩法暂未开启。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "daily_limit", "今日次数已用完", "你今天的躲猫猫次数已经用完了，明天再来。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "already_active", "正在选择地点", "你有一局躲猫猫正在选择地点，请先用 /躲 编号 完成选择。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "not_enough_scenes", "地点不足", "当前可用躲猫猫地点不足 7 个，请联系管理员配置。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "started", "选择躲藏地点", "{昵称}，躲猫猫开始，开局不扣除。若被系统找到，将扣除 {入场费} {货币}。\n请选择一个地点：\n{场景列表}\n请在 {选择超时分钟} 分钟内发送 /躲 编号。", ("{昵称}", "{入场费}", "{货币}", "{场景列表}", "{选择超时分钟}", "{日期}")),
    TemplateDefinition("/摸鱼躲猫猫", "invalid_scene", "地点编号无效", "请输入本局展示的 1 至 7 号地点。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "no_active_game", "没有进行中的游戏", "你当前没有等待选择地点的躲猫猫游戏。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "expired", "游戏已取消", "选择已超时，本局已取消，次数已返还。", ("{日期}",)),
    TemplateDefinition("/摸鱼躲猫猫", "first_round_missed", "第一轮未命中", "【系统巡查·第一轮】巡查 {巡查地点}\n奇怪，人躲哪里去了.......", ("{昵称}", "{巡查地点}", "{巡查过程}", "{日期}")),
    TemplateDefinition("/摸鱼躲猫猫", "found_first_round", "第一轮被找到", "【系统巡查·第一轮】巡查 {巡查地点}\n你被系统找到了，本局扣除 {惩罚金额} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{巡查地点}", "{巡查过程}", "{惩罚金额}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/摸鱼躲猫猫", "found", "第二轮被找到", "【系统巡查·第二轮】巡查 {巡查地点}\n你被系统找到了，本局扣除 {惩罚金额} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{巡查地点}", "{巡查过程}", "{惩罚金额}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/摸鱼躲猫猫", "won", "躲藏成功", "【系统巡查·第二轮】巡查 {巡查地点}\n躲藏成功，获得 {奖励} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{巡查地点}", "{巡查过程}", "{奖励}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/记忆考核", "usage", "玩法说明", "发送 /记忆考核 发起单人挑战；答对后发送 /继续 或 /收手。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "disabled", "玩法未开启", "记忆考核暂未开启。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "daily_limit", "今日次数已用完", "你今天已经完成过记忆考核挑战，明天再来。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "duel_daily_limit", "对战次数已用完", "你今天可发起的多人小游戏次数已用完。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "already_active", "考核正在进行", "当前有一场记忆考核正在进行，请稍后再试。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "multiplayer_active", "多人玩法进行中", "当前已有多人玩法进行中，暂不能发起记忆考核对战。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "random_event_active", "随机事件优先", "当前随机事件正在报名或进行中，暂不能发起或加入记忆考核。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "started", "展示考题", "【记忆考核·第 {等级} 级】请记住：{考核文本}", ("{昵称}", "{等级}", "{考核文本}", "{撤回秒数}", "{日期}")),
    TemplateDefinition("/记忆考核", "duel_waiting", "等待对手", "{昵称} 发起了记忆考核对战，另一位员工请发送 /加入 入局。", ("{昵称}", "{等级}", "{日期}")),
    TemplateDefinition("/记忆考核", "duel_started", "对战考题", "【记忆考核对战·第 {等级} 级】请记住：{考核文本}", ("{昵称}", "{等级}", "{考核文本}", "{撤回秒数}", "{日期}")),
    TemplateDefinition("/记忆考核", "duel_won", "对战胜利", "{昵称} 最先答对，赢得奖池 {奖励} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{奖励}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/记忆考核", "duel_incorrect", "对战答错", "答案不正确，本次扣除 {惩罚金额} {货币} 并加入奖池。", ("{昵称}", "{惩罚金额}", "{货币}", "{日期}")),
    TemplateDefinition("/记忆考核", "duel_disqualified", "对战不合格", "已达到答错上限，判定不合格。另一位员工仍可继续作答。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "duel_collected", "对战结束", "双方均未通过记忆考核，奖池已由系统回收。", ("{日期}",)),
    TemplateDefinition("/记忆考核", "correct", "本级通过", "第 {等级} 级通过。现在收手可获得 {奖励} {货币}，或发送 /继续 挑战下一层。", ("{昵称}", "{等级}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/记忆考核", "completed", "全部通关", "恭喜 {昵称} 完成第 {等级} 级记忆考核，获得 {奖励} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{等级}", "{奖励}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/记忆考核", "failed", "考核失败", "答案不正确，本次记忆考核未获得奖励。", ("{昵称}", "{日期}")),
    TemplateDefinition("/记忆考核", "no_active_game", "没有进行中的考核", "当前没有可作答的记忆考核。", ("{日期}",)),
    TemplateDefinition("/继续", "continued", "下一层开始", "【记忆考核·第 {等级} 级】请记住：{考核文本}", ("{昵称}", "{等级}", "{考核文本}", "{撤回秒数}", "{日期}")),
    TemplateDefinition("/继续", "cannot_continue", "无法继续", "当前没有通过且等待继续的单人记忆考核。", ("{日期}",)),
    TemplateDefinition("/收手", "cashed_out", "结算成功", "{昵称} 收手成功，获得 {奖励} {货币}。当前余额：{余额} {货币}。", ("{昵称}", "{奖励}", "{余额}", "{货币}", "{日期}")),
    TemplateDefinition("/收手", "cannot_cash_out", "无法收手", "当前没有可收手结算的单人记忆考核。", ("{日期}",)),
    TemplateDefinition("/投降", "lost", "投降结束", "{昵称} 投降，{胜者} 赢得奖池 {奖励} {货币}。", ("{昵称}", "{胜者}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/投降", "cannot_surrender", "无法投降", "当前没有可投降的记忆考核对战。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "usage", "创建报名局", "请用 /谁是卧底 人数 创建 4 至 8 人报名局。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "signup_started", "报名开启", "【谁是卧底】报名开启，目标 {人数} 人。当前 {当前人数} 人，请已与总监事建立私聊的员工发送 /加入。", ("{人数}", "{当前人数}", "{日期}")),
    TemplateDefinition("/谁是卧底", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再发起谁是卧底。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "disabled", "玩法未开启", "谁是卧底玩法暂未开启。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "daily_limit", "次数用尽", "你今天可发起的多人小游戏次数已用完。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "multiplayer_active", "多人玩法进行中", "当前已有多人玩法进行中，暂不能发起谁是卧底。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "already_active", "已有对局", "当前已有谁是卧底对局，请等待本局结束。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "invalid_player_count", "人数不正确", "谁是卧底人数只能是 4 至 8 人。", ("{日期}",)),
    TemplateDefinition("/谁是卧底", "delivery_failed", "身份牌发放失败", "【谁是卧底】身份私聊发放失败，所有旧身份牌已作废；其他玩家保留报名，发放失败的玩家请发送 /加入。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_joined", "卧底报名成功", "{昵称} 已加入谁是卧底，当前 {当前人数}/{人数} 人。", ("{昵称}", "{当前人数}", "{人数}", "{日期}")),
    TemplateDefinition("/加入", "undercover_dealing", "正在发牌", "【谁是卧底】人员已齐，正在私聊发放身份，请稍候。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_queued", "已进入候场", "本局谁是卧底已开始，你已进入下一局候场队列。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再加入谁是卧底。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_already_joined", "已报名", "你已经在当前谁是卧底对局中。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_cannot_rejoin", "无法重新加入", "你已退出当前谁是卧底对局，不能重新加入。", ("{日期}",)),
    TemplateDefinition("/加入", "undercover_not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/开始投票", "started", "投票开始", "【谁是卧底】投票开始，请在 {投票秒数} 秒内发送 /投票 序号。\n存活玩家：{存活玩家}", ("{投票秒数}", "{存活玩家}", "{日期}")),
    TemplateDefinition("/开始投票", "cannot_start", "无法投票", "当前不能开始投票；仅存活玩家可在描述阶段或并列补充发言后发起。", ("{日期}",)),
    TemplateDefinition("/投票", "usage", "投票格式", "请用 /投票 序号 投给一名存活玩家。", ("{日期}",)),
    TemplateDefinition("/投票", "recorded", "已记录投票", "【谁是卧底】{编号}号 {玩家名称} 已投票（{已完成人数}/{存活人数}）。", ("{编号}", "{玩家名称}", "{已完成人数}", "{存活人数}", "{日期}")),
    TemplateDefinition("/投票", "duplicate", "已投票", "本轮你已经投过票，不能修改。", ("{日期}",)),
    TemplateDefinition("/投票", "already_abstained", "本轮已弃票", "你本轮已经弃票，不能再投票。", ("{日期}",)),
    TemplateDefinition("/投票", "timeout_abstention", "超时自动弃票", "【谁是卧底】投票时间结束。{弃票玩家列表} 未投票，本轮自动弃票。", ("{弃票玩家列表}", "{日期}")),
    TemplateDefinition("/投票", "invalid_target", "目标无效", "该序号不是存活玩家，请重新确认。", ("{日期}",)),
    TemplateDefinition("/投票", "cannot_vote", "无法投票", "当前不能投票，或你已不在本局存活玩家中。", ("{日期}",)),
    TemplateDefinition("/投票", "tied", "投票并列", "【谁是卧底】{并列玩家} 票数并列，请补充发言；任意存活玩家发送 /开始投票 开启下一轮。", ("{并列玩家}", "{日期}")),
    TemplateDefinition("/投票", "eliminated", "淘汰玩家", "【谁是卧底】{淘汰玩家} 出局，身份：{身份}。请继续描述。", ("{淘汰玩家}", "{身份}", "{日期}")),
    TemplateDefinition("/投票", "settled", "对局结束", "【谁是卧底】{胜利阵营}阵营获胜。\n平民词：{平民词}\n卧底词：{卧底词}\n本轮淘汰：{淘汰情况}\n手动弃票：{手动弃票}\n超时弃票：{超时弃票}\n下一轮退出：{下一轮退出}\n全部身份：\n{全部身份}\n发送 /继续 可开启下一局。", ("{胜利阵营}", "{平民词}", "{卧底词}", "{淘汰情况}", "{手动弃票}", "{超时弃票}", "{下一轮退出}", "{全部身份}", "{日期}")),
    TemplateDefinition("/跳过", "undercover_usage", "卧底弃票格式", "谁是卧底投票阶段请发送 /跳过 编号。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_abstained", "卧底手动弃票", "【谁是卧底】{编号}号 {玩家名称} 本轮弃票（{已完成人数}/{存活人数}，已投票 {投票人数} 人、弃票 {弃票人数} 人）。", ("{编号}", "{玩家名称}", "{已完成人数}", "{存活人数}", "{投票人数}", "{弃票人数}", "{日期}")),
    TemplateDefinition("/跳过", "undercover_cannot_skip_self", "不能跳过自己", "不能让自己弃票；请由另一名存活玩家操作。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_already_voted", "目标已经投票", "该玩家本轮已经投票，不能再标记弃票。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_already_abstained", "目标已经弃票", "该玩家本轮已经弃票。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_invalid_target", "卧底目标无效", "该编号不是当前存活玩家，请重新确认。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_cannot_skip", "无法标记弃票", "当前不能执行谁是卧底弃票，或你不是存活参与者。", ("{日期}",)),
    TemplateDefinition("/跳过", "undercover_vote_expired", "全员弃票", "【谁是卧底】本轮无人投票，继续自由发言。", ("{日期}",)),
    TemplateDefinition("/退出谁是卧底", "left", "已退出", "你已退出当前谁是卧底对局。", ("{日期}",)),
    TemplateDefinition("/退出谁是卧底", "leave_after_round", "下一轮退出", "【谁是卧底】{编号}号 {玩家名称} 已申请下一轮退出，本轮仍正常参与。", ("{编号}", "{玩家名称}", "{日期}")),
    TemplateDefinition("/退出谁是卧底", "settled", "对局结束", "你已退出，{胜利阵营}阵营获胜。", ("{胜利阵营}", "{日期}")),
    TemplateDefinition("/退出谁是卧底", "cannot_leave", "无法退出", "当前没有你可以退出的谁是卧底对局。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "ended", "游戏已结束", "【谁是卧底】本局已由参与者结束。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "cannot_end", "无法结束", "当前没有你可以结束的谁是卧底对局。", ("{日期}",)),
    TemplateDefinition("/继续", "undercover_dealing", "正在发牌", "【谁是卧底】下一局人员已确认，正在私聊发放身份，请稍候。", ("{日期}",)),
    TemplateDefinition("/继续", "undercover_insufficient", "人数不足", "下一局可参与人数不足 4 人，暂不能开始。", ("{日期}",)),
    TemplateDefinition("/继续", "undercover_cannot_continue", "无法继续", "当前没有等待继续的谁是卧底对局。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "usage", "创建格式", "请用 /甩锅游戏 2-10 创建报名局。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "signup_started", "报名开启", "【甩锅游戏】{昵称} 发起了 {人数} 人局，当前 {当前人数}/{人数} 人，请发送 /加入 报名。", ("{昵称}", "{人数}", "{当前人数}", "{日期}")),
    TemplateDefinition("/甩锅游戏", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "disabled", "玩法关闭", "甩锅游戏暂未开启。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "insufficient_balance", "余额不足", "发起本局至少需要 {保证金} {货币}。", ("{保证金}", "{货币}", "{日期}")),
    TemplateDefinition("/甩锅游戏", "daily_limit", "次数用尽", "你今天可发起的多人小游戏次数已用完。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "incident_unavailable", "事故卡不可用", "当前没有可用的甩锅事故卡。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "multiplayer_active", "玩法冲突", "当前已有多人玩法进行中。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "already_active", "已有甩锅局", "当前已有甩锅游戏，请等待本局结束。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "signup_expired", "报名超时", "【甩锅游戏】报名超时，本局已解散。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "exploded", "锅已爆炸", "【甩锅游戏】锅爆炸了，{失败者} 背锅，扣除 {扣除金额} {货币}；{获胜者} 获胜，每人获得 {奖励} {货币}。", ("{失败者}", "{扣除金额}", "{获胜者}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/甩锅游戏", "turn_timeout", "操作超时", "【甩锅游戏】操作超时，{失败者} 背锅，扣除 {扣除金额} {货币}；{获胜者} 获胜，每人获得 {奖励} {货币}。", ("{失败者}", "{扣除金额}", "{获胜者}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/甩锅游戏", "temperature_warm", "温热提示", "【甩锅游戏】当前温度：温热。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "temperature_hot", "发烫提示", "【甩锅游戏】当前温度：发烫。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "temperature_burning", "滚烫提示", "【甩锅游戏】当前温度：滚烫。", ("{日期}",)),
    TemplateDefinition("/甩锅游戏", "temperature_exploding", "即将爆炸提示", "【甩锅游戏】当前温度：即将爆炸。", ("{日期}",)),
    TemplateDefinition("/加入", "blame_joined", "甩锅报名成功", "{昵称} 已加入甩锅游戏，当前 {当前人数}/{人数} 人。", ("{昵称}", "{当前人数}", "{人数}", "{日期}")),
    TemplateDefinition("/加入", "blame_started", "甩锅开局", "【甩锅游戏】人员已齐！\n参与者：{玩家列表}\n事故：{事故名称}\n{事故描述}\n必用关键词：{关键词}\n首位持锅者：{持锅者}\n当前温度：{温度}", ("{玩家列表}", "{事故名称}", "{事故描述}", "{关键词}", "{持锅者}", "{温度}", "{日期}")),
    TemplateDefinition("/加入", "blame_game_started", "进行中拒绝加入", "本局甩锅游戏已经开始，请结束后重新创建或报名。", ("{日期}",)),
    TemplateDefinition("/加入", "blame_failed", "甩锅报名失败", "{原因}", ("{原因}", "{日期}")),
    TemplateDefinition("/甩锅", "usage", "甩锅格式", "请用 /甩锅 玩家编号 甩锅理由。", ("{日期}",)),
    TemplateDefinition("/甩锅", "transferred", "甩锅成功", "{原持锅者} 把锅甩给了 {新持锅者}。当前温度：{温度}", ("{原持锅者}", "{新持锅者}", "{温度}", "{日期}")),
    TemplateDefinition("/甩锅", "missing_keywords", "关键词缺失", "甩锅理由缺少关键词：{缺少关键词}。", ("{缺少关键词}", "{日期}")),
    TemplateDefinition("/甩锅", "duplicate_reason", "话术重复", "这句话术已经成功使用过，请换一种说法。", ("{日期}",)),
    TemplateDefinition("/甩锅", "invalid_target", "目标无效", "目标编号无效，请选择本局另一名玩家。", ("{日期}",)),
    TemplateDefinition("/甩锅", "self_target", "不能甩给自己", "不能把锅甩给自己。", ("{日期}",)),
    TemplateDefinition("/甩锅", "immediate_return_blocked", "禁止立即回甩", "三人及以上时不能立即把锅甩回上一位玩家。", ("{日期}",)),
    TemplateDefinition("/甩锅", "not_holder", "非持锅者", "现在不是你持锅，不能甩锅。", ("{日期}",)),
    TemplateDefinition("/甩锅", "settled", "已爆锅", "【甩锅游戏】本局结束，{失败者} 背锅，扣除 {扣除金额} {货币}；{获胜者} 获胜，每人获得 {奖励} {货币}。", ("{失败者}", "{扣除金额}", "{获胜者}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/退出甩锅", "left_signup", "退出报名", "你已退出甩锅游戏报名。", ("{日期}",)),
    TemplateDefinition("/退出甩锅", "settled", "主动退出", "【甩锅游戏】{失败者} 主动退出并背锅，扣除 {扣除金额} {货币}；{获胜者} 获胜，每人获得 {奖励} {货币}。", ("{失败者}", "{扣除金额}", "{获胜者}", "{奖励}", "{货币}", "{日期}")),
    TemplateDefinition("/退出甩锅", "cannot_leave", "无法退出", "当前没有你可以退出的甩锅游戏。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "blame_cancelled", "甩锅游戏终止", "【甩锅游戏】本局已结束，全部保证金已退回。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "usage", "创建格式", "请发送 /蹦蹦数字炸弹 创建普通局，或发送 /蹦蹦数字炸弹 积分赛 创建固定8人、12轮积分赛。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "signup_started", "报名开启", "【蹦蹦数字炸弹】{昵称} 发起了报名，当前 {当前人数} 人，请发送 /加入 报名；至少3人后任一参与者发送 /开始。", ("{昵称}", "{当前人数}", "{日期}")),
    TemplateDefinition("/蹦蹦数字炸弹", "points_signup_started", "积分赛报名开启", "【蹦蹦数字炸弹积分赛】{昵称} 发起了固定 8 人、12 轮积分赛，当前 {当前人数}/8 人；请发送 /加入 报名，第8人加入后自动开始。", ("{昵称}", "{当前人数}", "{日期}")),
    TemplateDefinition("/蹦蹦数字炸弹", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再发起蹦蹦数字炸弹。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "disabled", "玩法关闭", "蹦蹦数字炸弹当前未开放。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "daily_limit", "次数用尽", "你今天可发起的多人小游戏次数已用完。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "multiplayer_active", "玩法冲突", "当前已有游戏或随机事件进行中。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "already_active", "已有对局", "当前已有蹦蹦数字炸弹对局。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "signup_timeout", "报名超时", "【蹦蹦数字炸弹】报名等待超时，本场已自动取消。", ("{日期}",)),
    TemplateDefinition("/蹦蹦数字炸弹", "unreported_reminder", "未报数提醒", "【蹦蹦数字炸弹】尚未报数：{玩家列表}。参与者现在可以发送 /跳过 编号 排除未报数玩家。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/加入", "number_bomb_joined", "数字炸弹报名", "{昵称} 已加入蹦蹦数字炸弹，当前 {当前人数} 人。", ("{昵称}", "{当前人数}", "{日期}")),
    TemplateDefinition("/加入", "number_bomb_direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再加入蹦蹦数字炸弹。", ("{日期}",)),
    TemplateDefinition("/加入", "number_bomb_started", "数字炸弹开局", "【蹦蹦数字炸弹】第 {轮次} 轮 - {惩罚类型}\n参与者：{玩家列表}\n请各位私聊总监事发送 /报数 1-100。", ("{轮次}", "{惩罚类型}", "{玩家列表}", "{日期}")),
    TemplateDefinition("/加入", "number_bomb_queued", "下一轮候选", "你已进入蹦蹦数字炸弹下一轮候选名单。", ("{日期}",)),
    TemplateDefinition("/加入", "number_bomb_next_round_full", "下一轮已满", "蹦蹦数字炸弹下一轮人数已满。", ("{日期}",)),
    TemplateDefinition("/加入", "number_bomb_already_joined", "已经加入", "你已经在当前蹦蹦数字炸弹对局中。", ("{日期}",)),
    TemplateDefinition("/加入", "number_bomb_not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/开始", "number_bomb_started", "数字炸弹开局", "【蹦蹦数字炸弹】第 {轮次} 轮 - {惩罚类型}\n参与者：{玩家列表}\n报数提示已私发，请按提示完成报数。", ("{轮次}", "{惩罚类型}", "{玩家列表}", "{日期}")),
    TemplateDefinition("/开始", "number_bomb_private_prompt", "私聊报数提示", "请按这个格式报数给我 /报数 数字", ("{日期}",)),
    TemplateDefinition("/开始", "number_bomb_insufficient", "人数不足", "当前仅 {当前人数} 人，至少3名参与者才能开始。", ("{当前人数}", "{日期}")),
    TemplateDefinition("/开始", "number_bomb_missing_direct_chats", "私聊未建立", "以下参与者尚未与总监事建立私聊，暂不能开始：{玩家列表}。请相关玩家先私聊总监事至少发送一条消息。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/开始", "number_bomb_cannot_start", "无法开始", "当前没有你可以开始的报名局。", ("{日期}",)),
    TemplateDefinition("/开始", "no_current_game", "暂无游戏", "当前没有你可以开始的游戏。", ("{日期}",)),
    TemplateDefinition("/退出", "number_bomb_signup_left", "退出报名", "你已退出蹦蹦数字炸弹报名。", ("{日期}",)),
    TemplateDefinition("/退出", "number_bomb_exit_queued", "下一轮退出", "你将在本轮结算后退出，当前轮仍需私聊报数。", ("{日期}",)),
    TemplateDefinition("/退出", "number_bomb_candidate_cancelled", "取消候选", "你已取消加入蹦蹦数字炸弹下一轮。", ("{日期}",)),
    TemplateDefinition("/退出", "number_bomb_retired", "退出积分赛", "你已退出积分赛；当前未报数轮记 -3 分，后续每轮 -3 分，且不再接收报数私聊。", ("{日期}",)),
    TemplateDefinition("/退出", "number_bomb_cannot_leave", "无法退出", "当前没有你可以退出的蹦蹦数字炸弹对局。", ("{日期}",)),
    TemplateDefinition("/退出", "memory_waiting_cancelled", "取消等待对战", "【记忆考核对战】等待报名已取消。", ("{日期}",)),
    TemplateDefinition("/退出", "memory_waiting_cannot_cancel", "无法取消等待", "当前没有你可以取消的记忆考核对战。", ("{日期}",)),
    TemplateDefinition("/报数", "group_only", "仅限私聊", "请私聊总监事发送 /报数 1-100，群内报数不会生效。", ("{日期}",)),
    TemplateDefinition("/报数", "submitted", "报数成功", "报数成功，本轮数字已锁定。", ("{日期}",)),
    TemplateDefinition("/报数", "invalid_number", "数字无效", "请发送 /报数 1-100，数字必须是范围内的整数。", ("{日期}",)),
    TemplateDefinition("/报数", "ambiguous_group", "请选择群聊", "你同时参加了多个群的蹦蹦数字炸弹，请发送 /报数 群序号 数字：\n{群聊列表}", ("{群聊列表}", "{日期}")),
    TemplateDefinition("/报数", "invalid_group", "群序号无效", "群序号无效，请按最新列表发送 /报数 群序号 数字：\n{群聊列表}", ("{群聊列表}", "{日期}")),
    TemplateDefinition("/报数", "duplicate", "重复报数", "你本轮已经报过数，不能修改。", ("{日期}",)),
    TemplateDefinition("/报数", "not_participant", "非参与者", "你不是当前轮参与者，无法报数。", ("{日期}",)),
    TemplateDefinition("/报数", "not_collecting", "未收数", "当前没有正在收集数字的蹦蹦数字炸弹轮次。", ("{日期}",)),
    TemplateDefinition("/报数", "result", "本轮结果", "{结果正文}", ("{结果正文}", "{日期}")),
    TemplateDefinition("/跳过", "usage", "跳过格式", "请发送 /跳过 编号，可一次填写多个编号，例如 /跳过 2 4。", ("{日期}",)),
    TemplateDefinition("/跳过", "not_enabled", "尚未开放", "首次未报数提醒后才能使用 /跳过。", ("{日期}",)),
    TemplateDefinition("/跳过", "not_participant", "无权操作", "只有本轮参与者可以跳过未报数玩家。", ("{日期}",)),
    TemplateDefinition("/跳过", "invalid_target", "目标无效", "跳过目标无效；请使用提醒中的玩家编号，或填写唯一的完整名称。", ("{日期}",)),
    TemplateDefinition("/跳过", "ambiguous_target", "名称重名", "该名称对应多名玩家，请改用编号。", ("{日期}",)),
    TemplateDefinition("/跳过", "duplicate_target", "目标重复", "跳过目标中有重复编号，请去重后重试。", ("{日期}",)),
    TemplateDefinition("/跳过", "already_submitted", "已经报数", "目标已经完成报数，不能跳过。", ("{日期}",)),
    TemplateDefinition("/跳过", "no_game", "无法跳过", "当前没有可执行跳过的蹦蹦数字炸弹报数轮。", ("{日期}",)),
    TemplateDefinition("/跳过", "no_current_game", "没有匹配游戏", "当前没有可执行跳过的游戏。", ("{日期}",)),
    TemplateDefinition("/跳过", "skipped", "移除玩家", "已从整场移除：{玩家列表}。本轮继续等待其他玩家报数。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/跳过", "settled", "移除并结算", "已从整场移除：{玩家列表}。其余玩家均已报数，立即结算本轮。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/跳过", "points_skipped", "积分赛跳过", "已跳过本轮未报数玩家：{玩家列表}。该玩家本轮 -3 分，下轮仍可继续参加。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/跳过", "points_settled", "积分赛跳过并结算", "已跳过本轮未报数玩家：{玩家列表}。该玩家本轮 -3 分、下轮仍可参加；其余玩家均已报数，立即结算本轮。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/跳过", "ended_insufficient", "人数不足结束", "已从整场移除：{玩家列表}。剩余参与者不足3人，本场游戏结束。", ("{玩家列表}", "{日期}")),
    TemplateDefinition("/继续", "number_bomb_started", "下一轮开始", "【蹦蹦数字炸弹】第 {轮次} 轮 - {惩罚类型}\n参与者：{玩家列表}\n报数提示已私发，请按提示完成报数。", ("{轮次}", "{惩罚类型}", "{玩家列表}", "{日期}")),
    TemplateDefinition("/继续", "number_bomb_insufficient", "人数不足", "下一轮参与者不足3人，本场游戏结束。", ("{日期}",)),
    TemplateDefinition("/继续", "number_bomb_cannot_continue", "无法继续", "当前没有等待继续的蹦蹦数字炸弹对局。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "number_bomb_ended", "数字炸弹结束", "【蹦蹦数字炸弹】本场已由参与者结束。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "number_bomb_cannot_end", "无法结束", "当前没有你可以结束的蹦蹦数字炸弹对局。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "memory_use_exit", "记忆考核结束方式", "已命中当前记忆考核；对战开始后请发送 /退出 执行投降，等待对手阶段可直接取消。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "no_current_game", "暂无游戏", "当前没有你可以结束的游戏。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "admin_forced", "管理员强制结束", "【{游戏}】管理员已强制结束当前游戏。", ("{游戏}", "{日期}")),
    TemplateDefinition("/结束游戏", "memory_waiting_cancelled", "取消等待对战", "【记忆考核对战】等待报名已取消。", ("{日期}",)),
    TemplateDefinition("/结束游戏", "memory_waiting_cannot_cancel", "无法取消等待", "当前没有你可以取消的记忆考核对战。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "usage", "创建格式", "请发送 /德州扑克 带入金额，例如 /德州扑克 20。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "created", "报名开启", "【德州扑克报名】{昵称} 发起了一局，统一带入 {带入} {货币}。当前 1 人，请发送 /加入；至少 {最少人数} 人后任一参与者发送 /开始。", ("{昵称}", "{带入}", "{货币}", "{最少人数}", "{日期}")),
    TemplateDefinition("/德州扑克", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再发起德州扑克。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "disabled", "玩法关闭", "德州扑克当前未开放。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "invalid_buy_in", "带入无效", "带入金额必须在 {最低带入} 至 {最高带入} {货币}之间。", ("{最低带入}", "{最高带入}", "{货币}", "{日期}")),
    TemplateDefinition("/德州扑克", "insufficient_balance", "余额不足", "余额不足，无法支付本局带入。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "daily_limit", "次数用尽", "你今天发起德州扑克的次数已经用完。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "already_active", "已有牌局", "当前群已有德州扑克牌局。", ("{日期}",)),
    TemplateDefinition("/德州扑克", "multiplayer_active", "玩法冲突", "当前群已有游戏或随机事件进行中。", ("{日期}",)),
    TemplateDefinition("/加入", "texas_joined", "德州报名成功", "{昵称} 已加入德州扑克，当前 {当前人数} 人。", ("{昵称}", "{当前人数}", "{日期}")),
    TemplateDefinition("/加入", "texas_already_joined", "已经报名", "你已经在当前德州扑克牌局中。", ("{日期}",)),
    TemplateDefinition("/加入", "texas_direct_chat_required", "需要私聊", "请先私聊总监事至少发送一条消息，再加入德州扑克。", ("{日期}",)),
    TemplateDefinition("/加入", "texas_insufficient_balance", "余额不足", "余额不足，无法支付统一带入。", ("{日期}",)),
    TemplateDefinition("/加入", "texas_full", "牌桌已满", "当前德州扑克已经满员。", ("{日期}",)),
    TemplateDefinition("/加入", "texas_cannot_join", "无法加入", "当前没有可加入的德州扑克报名局。", ("{日期}",)),
    TemplateDefinition("/开始", "texas_dealing", "正在发牌", "【德州扑克】{人数} 名玩家已就位，正在私聊发牌；所有底牌送达后自动进入翻前行动。", ("{人数}", "{日期}")),
    TemplateDefinition("/开始", "texas_insufficient_players", "人数不足", "当前人数不足，至少 {最少人数} 人才能开始德州扑克。", ("{最少人数}", "{日期}")),
    TemplateDefinition("/开始", "texas_missing_direct_chats", "私聊缺失", "有参与者尚未建立私聊，暂不能发牌。", ("{日期}",)),
    TemplateDefinition("/开始", "texas_cannot_start", "无法开始", "当前没有你可以开始的德州扑克报名局。", ("{日期}",)),
    TemplateDefinition("/退出", "texas_signup_left", "退出报名", "你已退出德州扑克报名，带入金额已退还。", ("{日期}",)),
    TemplateDefinition("/退出", "texas_folded", "本手弃牌", "你已退出本手德州扑克，按弃牌处理。", ("{日期}",)),
    TemplateDefinition("/退出", "texas_cannot_leave", "无法退出", "当前没有你可以退出的德州扑克。", ("{日期}",)),
    TemplateDefinition("/看牌", "group_only", "仅限私聊", "请在私聊中发送 /看牌，群内不会展示底牌。", ("{日期}",)),
    TemplateDefinition("/看牌", "no_cards", "暂无底牌", "当前没有你可以查看的德州扑克底牌。", ("{日期}",)),
    TemplateDefinition("/看牌", "usage", "看牌格式", "请在私聊发送 /看牌；同时参加多桌时发送 /看牌 群序号。", ("{日期}",)),
    TemplateDefinition("/看牌", "choose_group", "选择群聊", "你同时参加了多个群的德州扑克，请发送 /看牌 群序号：\n{群聊列表}", ("{群聊列表}", "{日期}")),
    TemplateDefinition("/看牌", "invalid_group", "群序号无效", "群序号无效，请发送 /看牌 群序号：\n{群聊列表}", ("{群聊列表}", "{日期}")),
    TemplateDefinition("/结束游戏", "texas_cannot_end", "无权结束", "德州扑克发起人和参与者不能结束整局；你可以发送 /退出 按弃牌处理。", ("{日期}",)),
    TemplateDefinition("/过牌", "acted", "过牌成功", "{座位}号 {昵称} 过牌，投入 {投入}，剩余筹码 {剩余筹码}。当前底池 {底池} {货币}；下一位：{下一位}。", ("{座位}", "{昵称}", "{投入}", "{剩余筹码}", "{底池}", "{下一位}", "{货币}", "{日期}")),
    TemplateDefinition("/跟注", "acted", "跟注成功", "{座位}号 {昵称} 跟注 {投入}，剩余筹码 {剩余筹码}。当前底池 {底池} {货币}；下一位：{下一位}。", ("{座位}", "{昵称}", "{投入}", "{剩余筹码}", "{底池}", "{下一位}", "{货币}", "{日期}")),
    TemplateDefinition("/加注", "usage", "加注格式", "请发送 /加注 加到金额，例如 /加注 10。", ("{日期}",)),
    TemplateDefinition("/加注", "acted", "加注成功", "{座位}号 {昵称} 加注并投入 {投入}，剩余筹码 {剩余筹码}。当前底池 {底池} {货币}；下一位：{下一位}。", ("{座位}", "{昵称}", "{投入}", "{剩余筹码}", "{底池}", "{下一位}", "{货币}", "{日期}")),
    TemplateDefinition("/全下", "acted", "全下成功", "{座位}号 {昵称} 全下并投入 {投入}，剩余筹码 {剩余筹码}。当前底池 {底池} {货币}；下一位：{下一位}。", ("{座位}", "{昵称}", "{投入}", "{剩余筹码}", "{底池}", "{下一位}", "{货币}", "{日期}")),
    TemplateDefinition("/弃牌", "acted", "弃牌成功", "{座位}号 {昵称} 弃牌，投入 {投入}，剩余筹码 {剩余筹码}。当前底池 {底池} {货币}；下一位：{下一位}。", ("{座位}", "{昵称}", "{投入}", "{剩余筹码}", "{底池}", "{下一位}", "{货币}", "{日期}")),
    *(
        TemplateDefinition(command, "cannot_act", "无法行动", "当前不能执行该德州扑克行动：{原因}。", ("{原因}", "{日期}"))
        for command in ("/过牌", "/跟注", "/加注", "/全下", "/弃牌")
    ),
    TemplateDefinition("/上架暗网", "private_only", "仅限私聊", "请私聊总监事发送 /上架暗网。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "unavailable", "交易所关闭", "暗网交易所暂未开放。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "name", "填写商品名称", "请发送商品名称（1–30 字）。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "purpose", "填写商品用途", "请发送商品用途（1–100 字）。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "details", "填写商品详情", "请发送商品详细信息（1–500 字）。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "gender", "填写匿名性别", "请选择匿名性别并发送：男、女或保密。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "starting_price", "填写起拍价", "请发送起拍价（1–99999 的整数）。", ("{日期}",)),
    TemplateDefinition("/上架暗网", "preview", "草稿填写完成", "草稿已填写完成，请发送 /确认 正式上架。", ("{日期}",)),
    TemplateDefinition("/取消上架", "private_only", "仅限私聊", "请在私聊中发送 /取消上架。", ("{日期}",)),
    TemplateDefinition("/取消上架", "cancelled", "草稿已取消", "暗网上架草稿已取消。", ("{日期}",)),
    TemplateDefinition("/取消上架", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/取消上架", "no_draft", "没有草稿", "当前没有可取消的暗网上架草稿。", ("{日期}",)),
    TemplateDefinition("/确认", "private_only", "仅限私聊", "请在私聊中发送 /确认。", ("{日期}",)),
    TemplateDefinition("/确认", "listed", "上架成功", "暗网商品 #{商品编号} 上架成功。", ("{商品编号}", "{日期}")),
    TemplateDefinition("/确认", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/确认", "unavailable", "交易所关闭", "暗网交易所暂未开放。", ("{日期}",)),
    TemplateDefinition("/确认", "expired", "草稿超时", "暗网上架草稿已超时，请重新发送 /上架暗网。", ("{日期}",)),
    TemplateDefinition("/确认", "daily_limit", "次数用尽", "你今天的暗网商品上架次数已用完。", ("{日期}",)),
    TemplateDefinition("/确认", "no_draft", "没有完整草稿", "当前没有可确认的完整暗网上架草稿。", ("{日期}",)),
    TemplateDefinition("/报价", "private_only", "仅限私聊", "请在私聊中发送 /报价 商品编号 金额。", ("{日期}",)),
    TemplateDefinition("/报价", "usage", "报价格式", "请用 /报价 商品编号 金额，例如 /报价 12 25。", ("{日期}",)),
    TemplateDefinition("/报价", "accepted", "报价成功", "暗网商品 #{商品编号} 报价成功：{金额} {货币}，当前冻结 {冻结金额} {货币}。", ("{商品编号}", "{金额}", "{冻结金额}", "{货币}", "{日期}")),
    TemplateDefinition("/报价", "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/报价", "not_found", "商品不存在", "未找到该暗网商品。", ("{日期}",)),
    TemplateDefinition("/报价", "ended", "竞价结束", "该暗网商品已结束竞价。", ("{日期}",)),
    TemplateDefinition("/报价", "invalid_amount", "金额无效", "报价金额必须是 1–99999 的整数。", ("{日期}",)),
    TemplateDefinition("/报价", "insufficient_balance", "余额不足", "余额不足，无法提交该报价。", ("{日期}",)),
    TemplateDefinition("/报价", "too_low", "报价过低", "报价过低，下一次报价至少为 {最低报价} {货币}。", ("{最低报价}", "{货币}", "{日期}")),
    *(
        definition
        for command in ("/公开", "/不公开")
        for definition in (
            TemplateDefinition(command, "private_only", "仅限私聊", f"请在私聊中发送 {command}。", ("{日期}",)),
            TemplateDefinition(command, "usage", "确认格式", f"请用 {command} [商品编号]。", ("{日期}",)),
            TemplateDefinition(command, "choose_listing", "选择交易", "你有多笔待确认交易：{商品编号列表}。请在指令后加商品编号。", ("{商品编号列表}", "{日期}")),
            TemplateDefinition(command, "waiting_other", "等待另一方", "你的选择已记录，正在等待另一方确认。", ("{日期}",)),
            TemplateDefinition(command, "revealed", "身份已公开", "双方均同意，买卖双方身份已在暗网群公开。", ("{日期}",)),
            TemplateDefinition(command, "anonymous", "保持匿名", "本次交易将保持匿名。", ("{日期}",)),
            TemplateDefinition(command, "expired", "确认超时", "公开确认已超时，本次交易保持匿名。", ("{日期}",)),
            TemplateDefinition(command, "no_pending", "没有待确认交易", "当前没有需要你确认公开身份的暗网交易。", ("{日期}",)),
            TemplateDefinition(command, "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
        )
    ),
    TemplateDefinition("/查看暗网", "group_only", "仅限暗网群", "请在配置的暗网群中发送 /查看暗网。", ("{日期}",)),
    TemplateDefinition("/查看暗网", "usage", "查询格式", "请用 /查看暗网 或 /查看暗网 商品编号。", ("{日期}",)),
    TemplateDefinition("/查看暗网", "wrong_group", "群聊不匹配", "本群不是暗网交易所入口。", ("{日期}",)),
    TemplateDefinition("/查看暗网", "empty", "暂无商品", "暗网交易所当前没有竞价中的商品。", ("{日期}",)),
    TemplateDefinition("/查看暗网", "not_found", "商品不存在", "未找到该竞价中的暗网商品。", ("{日期}",)),
    TemplateDefinition("/查看暗网", "shown", "查询成功", "{商品列表}", ("{商品列表}", "{日期}")),
    *(
        definition
        for command, success_scenario, success_title, success_text in (
            ("/确认收货", "confirmed", "确认成功", "暗网商品 #{商品编号} 确认收货成功。"),
            ("/投诉", "complained", "投诉成功", "暗网商品 #{商品编号} 投诉已处理，成交款已退还，卖家已被处罚。"),
        )
        for definition in (
            TemplateDefinition(command, "private_only", "仅限私聊", f"请在私聊中发送 {command} [商品编号]。", ("{日期}",)),
            TemplateDefinition(command, "usage", "指令格式", f"请用 {command} [商品编号]。", ("{日期}",)),
            TemplateDefinition(command, "choose_listing", "选择交易", "你有多笔待收货交易：{商品编号列表}。请在指令后加商品编号。", ("{商品编号列表}", "{日期}")),
            TemplateDefinition(command, success_scenario, success_title, success_text, ("{商品编号}", "{日期}")),
            TemplateDefinition(command, "auto_confirmed", "已自动确认", "暗网商品 #{商品编号} 已到期自动确认收货。", ("{商品编号}", "{日期}")),
            TemplateDefinition(command, "no_pending", "没有待收货交易", "当前没有需要你处理的暗网待收货交易。", ("{日期}",)),
            TemplateDefinition(command, "not_found", "商品不存在", "未找到该暗网商品。", ("{日期}",)),
            TemplateDefinition(command, "not_buyer", "不是买家", "你不是该暗网商品的买家，无法处理收货。", ("{日期}",)),
            TemplateDefinition(command, "already_resolved", "订单已处理", "该暗网订单已经处理完成。", ("{日期}",)),
            TemplateDefinition(command, "not_joined", "未入职", "请先用 /入职 名字 加入摸鱼公司。", ("{日期}",)),
        )
    ),
    TemplateDefinition("/投稿", "usage", "投稿格式", "请发送 /投稿 随机事件。", ("{日期}",)),
    TemplateDefinition("/投稿", "not_joined", "未入职", "请先发送 /入职 名称 加入摸鱼公司。", ("{日期}",)),
    TemplateDefinition("/投稿", "no_direct_chat", "无法建立私聊", "暂时无法建立私聊，请先私聊机器人发送 /投稿 随机事件。", ("{日期}",)),
    TemplateDefinition("/投稿", "disabled", "投稿未开放", "随机事件投稿当前未开放。", ("{日期}",)),
    TemplateDefinition("/投稿", "transferred", "已转入私聊", "已转入私聊引导。", ("{日期}",)),
    TemplateDefinition("/投稿", "expired", "草稿已超时", "原投稿草稿已超时，已为你新建一份草稿。", ("{日期}",)),
    TemplateDefinition("/投稿", "prompt_scene_name", "询问场景名称", "请先发送场景名称（1～64 字）。", ("{日期}",)),
    TemplateDefinition("/投稿", "prompt_signup_text", "询问报名公告", "请发送随机事件报名公告（1～2000 字）。", ("{日期}",)),
    TemplateDefinition("/投稿", "prompt_participant_count", "询问参加人数", "请直接发送事件参加人数（1～{最大人数}）。", ("{最大人数}", "{日期}")),
    TemplateDefinition("/投稿", "prompt_role_name", "询问身份名称", "已分配 {已分配人数} / {总人数}，还剩 {剩余人数} 个席位。请发送身份名称。", ("{已分配人数}", "{总人数}", "{剩余人数}", "{日期}")),
    TemplateDefinition("/投稿", "prompt_role_capacity", "询问身份人数", "请发送身份人数：“{身份}”（剩余 {剩余人数}）。", ("{身份}", "{剩余人数}", "{日期}")),
    TemplateDefinition("/投稿", "prompt_event_name", "询问事件名称", "身份已分配完成。可用变量：{身份变量}\n请发送事件名称。", ("{身份变量}", "{日期}")),
    TemplateDefinition("/投稿", "prompt_event_opening", "询问剧情开场白", "请发送事件“{事件名称}”的正式剧情开场白。", ("{事件名称}", "{日期}")),
    TemplateDefinition("/投稿", "prompt_event_controls", "事件操作提示", "事件模板已保存。发送 /继续添加、/事件完成、/修改事件 编号 或 /删除事件 编号。", ("{日期}",)),
    TemplateDefinition("/投稿", "preview", "投稿预览", "{预览正文}", ("{预览正文}", "{日期}")),
    TemplateDefinition("/投稿", "invalid_input", "输入错误", "{错误}\n{当前提示}", ("{错误}", "{当前提示}", "{日期}")),
    TemplateDefinition("/投稿", "approved", "审核通过通知", "你的随机事件投稿「{场景名称}」已审核通过，获得 {通过奖励} 摸鱼币。", ("{场景名称}", "{通过奖励}", "{日期}")),
    TemplateDefinition("/投稿", "rejected", "审核拒绝通知", "你的随机事件投稿「{场景名称}」未通过审核。原因：{拒绝原因}", ("{场景名称}", "{拒绝原因}", "{日期}")),
    TemplateDefinition("/确认投稿", "incomplete", "投稿未完成", "投稿尚未完成，请继续填写当前项目。", ("{日期}",)),
    TemplateDefinition("/确认投稿", "daily_limit", "今日投稿次数已用完", "你今天已经投稿过一次，请明天再来。", ("{日期}",)),
    TemplateDefinition("/确认投稿", "submitted", "投稿已提交", "投稿 #{投稿编号} 已提交审核。", ("{投稿编号}", "{日期}")),
    TemplateDefinition("/取消投稿", "confirm", "取消确认", "确认取消当前投稿吗？发送 /确认取消投稿；发送 /上一步 返回。", ("{日期}",)),
    TemplateDefinition("/确认取消投稿", "required", "需要先申请取消", "请先发送 /取消投稿。", ("{日期}",)),
    TemplateDefinition("/确认取消投稿", "cancelled", "投稿已取消", "本次随机事件投稿已取消。", ("{日期}",)),
    TemplateDefinition("/我的投稿", "shown", "投稿列表", "{投稿列表}", ("{投稿列表}", "{日期}")),
    TemplateDefinition("/撤回投稿", "usage", "撤回格式", "格式：/撤回投稿 编号", ("{日期}",)),
    TemplateDefinition("/撤回投稿", "invalid_number", "投稿编号无效", "投稿编号无效。", ("{日期}",)),
    TemplateDefinition("/撤回投稿", "not_found", "没有可撤回投稿", "没有找到可撤回的待审核投稿。", ("{日期}",)),
    TemplateDefinition("/撤回投稿", "withdrawn", "投稿已撤回", "投稿 #{投稿编号} 已撤回。", ("{投稿编号}", "{日期}")),
)


def template_definition(command: str, scenario: str) -> TemplateDefinition:
    for definition in TEMPLATE_DEFINITIONS:
        if definition.command == command and definition.scenario == scenario:
            return definition
    raise ValueError("未知模板场景")


def definitions_for_command(command: str) -> tuple[TemplateDefinition, ...]:
    return tuple(
        definition
        for definition in TEMPLATE_DEFINITIONS
        if definition.command == command
    )


def validate_template(command: str, scenario: str, template: str) -> None:
    definition = template_definition(command, scenario)
    if not template.strip():
        raise ValueError("模板不能为空")
    if len(template) > _MAX_TEMPLATE_LENGTH:
        raise ValueError("模板不能超过 2000 个字符")
    allowed = set(definition.variables)
    for token in _TEMPLATE_TOKEN.findall(template):
        if f"{{{token}}}" not in allowed:
            raise ValueError(f"模板变量不支持：{{{token}}}")


def render_template(
    definition: TemplateDefinition, template: str, values: Mapping[str, object]
) -> str:
    validate_template(definition.command, definition.scenario, template)
    rendered = template
    for variable in definition.variables:
        if variable not in rendered:
            continue
        if variable not in values:
            raise ValueError(f"模板变量缺少值：{variable}")
        rendered = rendered.replace(variable, str(values[variable]))
    return rendered
